### ISSUE TITLE
Example notebook to test on custom data

### ISSUE THREAD

**Issue by aretius** [zdf-opensource/recommendations-models-sasrec#1]
Hello
I came across your repo through your great recsys talk! Thanks again for that.
It would be really helpful to have a sample notebook to test the implementations on custom data. 
As implementing a pipeline for custom use case will require significant changes.

**Comment by fnetzer-accso** [comment]
Thank you for your interest and for attending the talk!
 
The current codebase is part of our productive system, and we had to extract it specifically to make it accessible for the presentation. This means the implementation isn’t currently available as a standalone product, and adapting it to custom datasets may indeed require significant modifications.
That said, we're actively working to improve accessibility and modularity in upcoming releases. Our goal is to support more flexible use cases, and we hope to have a more adaptable framework with sample notebooks and documentation in the future.
Thanks for your patience, and please stay tuned for future updates!
